//
//  NewYorkTimesArticleSet.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB
class NewYorkTimesArticleSet: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _objectId: String?
    var _acquireDate: String?
    var _articles: [String]?
    var _numArticles: NSNumber?
    
    class func dynamoDBTableName() -> String {
        return "newsreader-mobilehub-429622615-NewYorkTimesArticleSet"
    }
    
    class func hashKeyAttribute() -> String {
        return "_objectId"
    }
    
    class func rangeKeyAttribute() -> String {
        return "_acquireDate"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_objectId" : "objectId",
               "_acquireDate" : "acquire_date",
               "_articles" : "articles",
               "_numArticles" : "num_articles",
        ]
    }
}
