//
//  NewYorkTimesArticle.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB
class NewYorkTimesArticle: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _objectId: String?
    var _abstract: String?
    var _byline: String?
    var _publishDate: String?
    var _section: String?
    var _subsection: String?
    var _title: String?
    var _url: String?
    
    class func dynamoDBTableName() -> String {
        return "newsreader-mobilehub-429622615-NewYorkTimesArticle"
    }
    
    class func hashKeyAttribute() -> String {
        return "_objectId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_objectId" : "objectId",
               "_abstract" : "abstract",
               "_byline" : "byline",
               "_publishDate" : "publish_date",
               "_section" : "section",
               "_subsection" : "subsection",
               "_title" : "title",
               "_url" : "url",
        ]
    }
}
